### ISSUE TITLE
Differentiate archived repo.

### ISSUE THREAD

**Issue by HerIsDia** [nazifbara/repos-timeline#17]
Hi. 👋🏻 
Before all, this is a cute project, congrats for that !

My idea is to differentiate archived repo from active repo.

I've got an idea of add transparency of archived repo, something like this:
![image](https://user-images.githubusercontent.com/67396485/154863663-13e61099-ed73-4d91-acf0-8101d4062853.png)
who "RSSToNotion" is the archived repo. (it's an example.)

Another idea is to make the color circle green for active repo and red for archived repo, something like this:
![image](https://user-images.githubusercontent.com/67396485/154863772-1947aadb-1b4e-4a68-b2df-ff4b69c0711c.png)
who "RSSToNotion" is the archived repo. (it's an example.)

Could be cool to see this. ^^

**Comment by nazifbara** [comment]
That could indeed be handy. Thanks for your interest.
